name = "PosDefManifold"
uuid = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
authors = ["congedom "]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
